/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as EventsRouteImport } from './routes/events'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => ClassesRoute,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunitiesRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/search': typeof SearchRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/search': typeof SearchRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/search': typeof SearchRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/classes'
    | '/communities'
    | '/events'
    | '/search'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/classes'
    | '/communities'
    | '/events'
    | '/search'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/classes'
    | '/communities'
    | '/events'
    | '/search'
    | '/classes/$classId'
    | '/communities/$communityId'
    | '/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface ClassesRouteChildren {
  ClassesClassIdRoute: typeof ClassesClassIdRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesClassIdRoute: ClassesClassIdRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface CommunitiesRouteChildren {
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ClassesRoute: ClassesRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
